import {
  Container,
  FormControl,
  InputGroup,
  Navbar,
  NavItem,
} from "react-bootstrap";
import Head from "next/head";
import React, { useContext, useState, useEffect } from "react";
import Link from "next/link";
import { Cart, Search } from "react-bootstrap-icons";
import Book from "../assets/education.svg";
import Image from "next/image";
import { BooksContext } from "../context/BookContext";
const Header = () => {
  const { books, setMyBooks, originalBooks, cart } = useContext(BooksContext);
  const [searchTerm, setSearchTerm] = useState("");
  useEffect(() => {
    const filteredBooks = books.filter(
      (book) =>
        book.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        book.author.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setMyBooks(filteredBooks);
    //setbooks to original books if search term is empty
    if (searchTerm === "") {
      setMyBooks(originalBooks);
    }
  }, [searchTerm]);
  return (
    <>
      <Head>
        <title>Book Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        expand="lg"
        style={{
          backgroundColor: "#A03037",
        }}
      >
        <Container>
          <Link href="/">
            <Navbar.Brand
              style={{
                color: "white",
                flex: "1",
                display: "flex",
                alignItems: "center",
                gap: "0.5rem",
                cursor: "pointer",
              }}
            >
              <Image src={Book} width={20} height={20} alt="Book" />
              BookStore
            </Navbar.Brand>
          </Link>
          <InputGroup
            style={{
              flex: 1,
            }}
          >
            <InputGroup.Text>
              <Search />
            </InputGroup.Text>
            <FormControl
              placeholder="Search"
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </InputGroup>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "flex-end",
              flex: "1",
              gap: "1rem",
            }}
          >
            <Link href="cart">
              <NavItem
                style={{
                  color: "white",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "flex-end",
                  gap: "0.5rem",
                  cursor: "pointer",
                  fontWeight: "bold",
                  position: "relative",
                }}
              >
                <Cart />
                Cart
                <span
                  className="position-absolute radius-circle bg-white text-black d-flex align-items-center justify-content-center"
                  style={{
                    borderRadius: " 50%",
                    height: 20,
                    width: 20,
                    fontSize: 12,
                    top: -10,
                    right: -10,
                  }}
                >
                  {cart.length}
                </span>
              </NavItem>
            </Link>
          </div>
        </Container>
      </Navbar>
    </>
  );
};

export default Header;
